const SUPABASE_URL="https://lhvbtioqqvvvprdmdhmi.supabase.co";const SUPABASE_KEY="sb_publishable_G8_JOzVzUvv1FXmsF31boQ_WbhPFZdS";const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);let store=null,items=[],connected=false,errorMsg='';const STORES={eurospin:{name:'EUROSPIN',cls:'euro'},esselunga:{name:'ESSELUNGA',cls:'essel'}};

let shoppingMode=false;
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadItems(){const {data,error}=await db.from('shopping_items').select('id,store,item,checked,created_at').order('created_at',{ascending:true});if(error){errorMsg=error.message;connected=false}else{items=data||[];errorMsg='';connected=true}render()}
async function addItem(){const el=document.getElementById('newitem');const value=el&&el.value.trim();if(!value||!store)return;el.value='';const {error}=await db.from('shopping_items').insert({store,item:value,checked:false});if(error){errorMsg=error.message;render()}}
async function toggle(id,value){const {error}=await db.from('shopping_items').update({checked:!value}).eq('id',id);if(error){errorMsg=error.message;render()}}
async function removeItem(id){const {error}=await db.from('shopping_items').delete().eq('id',id);if(error){errorMsg=error.message;render()}}
async function clearChecked(){if(!store)return;const {error}=await db.from('shopping_items').delete().eq('store',store).eq('checked',true);if(error){errorMsg=error.message;render()}}
async function transferChecked(){if(!store)return;const target=store==='eurospin'?'esselunga':'eurospin';const selected=items.filter(x=>x.store===store&&x.checked);if(!selected.length)return;const ids=selected.map(x=>x.id);const {error}=await db.from('shopping_items').update({store:target,checked:false}).in('id',ids);if(error){errorMsg=error.message;render()}}
function status(){return `<div class="status ${connected?'ok':'bad'}">${connected?'● Sincronizzato':'● '+esc(errorMsg||'Connessione...')}</div>`}
function home(){return `<div class="head"><div class="icon">🛒</div><h1>Spesa</h1><p>Scegli il supermercato</p></div><div class="stores">${Object.entries(STORES).map(([id,s])=>`<button class="store ${s.cls}" onclick="store='${id}';shoppingMode=false;render()"><div class="brand">${s.name}</div><div class="count">${items.filter(x=>x.store===id&&!x.checked).length} prodotti nella lista</div></button>`).join('')}</div>${status()}`}
function list(){const s=STORES[store];let list=items.filter(x=>x.store===store);if(shoppingMode)list=[...list].sort((a,b)=>Number(a.checked)-Number(b.checked));const selected=list.filter(x=>x.checked).length;const target=store==='eurospin'?'Esselunga':'Eurospin';return `<div class="${shoppingMode?'shopping-mode':''}">${shoppingMode?`<div class="shop-banner"><div><b>🛒 Sto facendo la spesa</b><small>Tocca il cerchio quando prendi un prodotto</small></div><button onclick="shoppingMode=false;render()">Esci</button></div>`:''}<header class="top"><button onclick="store=null;shoppingMode=false;render()" class="round">‹</button><div class="title"><p>LISTA SPESA</p><h1>${s.name}</h1></div><button onclick="loadItems()" class="round">↻</button></header>${!shoppingMode?`<div class="card"><div class="add"><input id="newitem" placeholder="Aggiungi un prodotto..." onkeydown="if(event.key==='Enter')addItem()"><button class="plus" onclick="addItem()">+</button></div></div>`:''}<div class="items">${list.length?list.map(x=>`<div class="item ${x.checked?'checked':''}"><button class="check" onclick="toggle(${x.id},${x.checked})"></button><span class="txt">${esc(x.item)}</span>${shoppingMode?'':`<button class="trash" onclick="removeItem(${x.id})">✕</button>`}</div>`).join(''):'<div class="empty">Lista vuota<br><small>Aggiungi il primo prodotto.</small></div>'}</div>${!shoppingMode&&list.length?'<button class="shop-start" onclick="shoppingMode=true;render()">🛒 STO FACENDO LA SPESA</button>':''}${selected?`<div class="selected-actions"><button class="clear" onclick="clearChecked()">Elimina acquistati (${selected})</button><button class="transfer" onclick="transferChecked()">Trasferisci ad ${target}</button></div>`:''}${status()}</div>`}
function render(){document.getElementById('app').innerHTML=`<div class="app">${store?list():home()}</div>`}
const channel=db.channel('shopping-items-live').on('postgres_changes',{event:'*',schema:'public',table:'shopping_items'},()=>loadItems()).subscribe(statusValue=>{connected=statusValue==='SUBSCRIBED';render()});
render();loadItems();
