const SUPABASE_URL="https://lhvbtioqqvvvprdmdhmi.supabase.co";const SUPABASE_KEY="sb_publishable_G8_JOzVzUvv1FXmsF31boQ_WbhPFZdS";const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);let store=null,items=[],connected=false,errorMsg='';const STORES={eurospin:{name:'EUROSPIN',cls:'euro'},esselunga:{name:'ESSELUNGA',cls:'essel'}};

let toastText='';let toastTimer=null;let dragId=null;
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showToast(m){toastText=m;render();clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toastText='';render()},2000)}function toast(){return toastText?`<div class="toast">${esc(toastText)}</div>`:''}
function orderKey(s){return 'spesa_local_order_'+s}function getOrder(s){try{return JSON.parse(localStorage.getItem(orderKey(s))||'[]').map(Number)}catch(e){return[]}}function saveOrder(s,ids){localStorage.setItem(orderKey(s),JSON.stringify(ids.map(Number)))}
function orderedList(s){const source=items.filter(x=>x.store===s),valid=new Set(source.map(x=>Number(x.id))),saved=getOrder(s).filter(id=>valid.has(id)),known=new Set(saved),incoming=source.filter(x=>!known.has(Number(x.id))).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)),merged=[...saved,...incoming.map(x=>Number(x.id))],map=new Map(source.map(x=>[Number(x.id),x]));saveOrder(s,merged);return merged.map(id=>map.get(id)).filter(Boolean)}
function dragStart(e,id){dragId=Number(id);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(id))}function dragOver(e){e.preventDefault()}function dropItem(e,to){e.preventDefault();const from=dragId||Number(e.dataTransfer.getData('text/plain')),ids=orderedList(store).map(x=>Number(x.id)),a=ids.indexOf(from),b=ids.indexOf(Number(to));if(a<0||b<0||a===b)return;ids.splice(a,1);ids.splice(b,0,from);saveOrder(store,ids);dragId=null;render()}function dragEnd(){dragId=null}
function suggestions(q){q=(q||'').trim().toLowerCase();if(!q)return[];const seen=new Set(),out=[];items.forEach(x=>{const n=String(x.item||'').trim(),k=n.toLowerCase();if(n&&k.includes(q)&&!seen.has(k)){seen.add(k);out.push(n)}});return out.slice(0,6)}function updateSuggestions(){const e=document.getElementById('newitem'),b=document.getElementById('suggestions');if(!e||!b)return;const v=suggestions(e.value);b.innerHTML=v.map(x=>`<button data-v="${esc(x)}" onclick="pickSuggestion(this.dataset.v)">${esc(x)}</button>`).join('');b.style.display=v.length?'grid':'none'}function pickSuggestion(v){const e=document.getElementById('newitem');e.value=v;document.getElementById('suggestions').style.display='none';e.focus()}
async function loadItems(){const {data,error}=await db.from('shopping_items').select('id,store,item,checked,created_at').order('created_at',{ascending:true});if(error){errorMsg=error.message;connected=false}else{items=data||[];errorMsg='';connected=true}render()}async function addItem(){const e=document.getElementById('newitem'),v=e&&e.value.trim();if(!v||!store)return;e.value='';const {error}=await db.from('shopping_items').insert({store,item:v,checked:false});if(error){errorMsg=error.message;render()}}async function toggle(id,v){const {error}=await db.from('shopping_items').update({checked:!v}).eq('id',id);if(error){errorMsg=error.message;render()}}async function removeItem(id){const {error}=await db.from('shopping_items').delete().eq('id',id);if(error){errorMsg=error.message;render()}}async function clearChecked(){const {error}=await db.from('shopping_items').delete().eq('store',store).eq('checked',true);if(error){errorMsg=error.message;render()}}
async function transferChecked(){const target=store==='eurospin'?'esselunga':'eurospin',sel=items.filter(x=>x.store===store&&x.checked);if(!sel.length)return;const {error}=await db.from('shopping_items').update({store:target,checked:false}).in('id',sel.map(x=>x.id));if(error){errorMsg=error.message;render();return}await loadItems();showToast(`${sel.length} ${sel.length===1?'prodotto trasferito':'prodotti trasferiti'} ad ${target==='esselunga'?'Esselunga':'Eurospin'}`)}
function status(){return `<div class="status ${connected?'ok':'bad'}">${connected?'● Sincronizzato':'● '+esc(errorMsg||'Connessione...')}</div>`}function home(){return `<div class="head"><div class="icon">🛒</div><h1>Spesa</h1><p>Scegli il supermercato</p></div><div class="stores">${Object.entries(STORES).map(([id,s])=>`<button class="store ${s.cls}" onclick="store='${id}';render()"><div class="brand">${s.name}</div><div class="count">${items.filter(x=>x.store===id&&!x.checked).length} prodotti nella lista</div></button>`).join('')}</div>${status()}<div class="disclaimer">registered da vinsDOTit v.2</div>${toast()}`}
function list(){const s=STORES[store],list=orderedList(store),selected=list.filter(x=>x.checked).length,target=store==='eurospin'?'Esselunga':'Eurospin';return `<div><header class="top"><button onclick="store=null;render()" class="round">‹</button><div class="title"><p>LISTA SPESA</p><h1>${s.name}</h1></div><button onclick="loadItems()" class="round">↻</button></header><div class="card"><div class="add"><input id="newitem" autocomplete="off" placeholder="Aggiungi un prodotto..." oninput="updateSuggestions()" onkeydown="if(event.key==='Enter')addItem()"><button class="plus" onclick="addItem()">+</button></div><div id="suggestions" class="suggestions"></div></div><div class="items">${list.length?list.map(x=>`<div class="item ${x.checked?'checked':''}" ondragover="dragOver(event)" ondrop="dropItem(event,${x.id})"><button class="handle" draggable="true" ondragstart="dragStart(event,${x.id})" ondragend="dragEnd()" aria-label="Sposta prodotto">☰</button><button class="check" onclick="toggle(${x.id},${x.checked})"></button><span class="txt">${esc(x.item)}</span><button class="trash" onclick="removeItem(${x.id})">✕</button></div>`).join(''):'<div class="empty">Lista vuota<br><small>Aggiungi il primo prodotto.</small></div>'}</div>${selected?`<div class="selected-actions"><button class="clear" onclick="clearChecked()">Elimina acquistati (${selected})</button><button class="transfer" onclick="transferChecked()">Trasferisci ad ${target}</button></div>`:''}${status()}${toast()}</div>`}function render(){document.getElementById('app').innerHTML=`<div class="app">${store?list():home()}</div>`}db.channel('shopping-items-live').on('postgres_changes',{event:'*',schema:'public',table:'shopping_items'},()=>loadItems()).subscribe(v=>{connected=v==='SUBSCRIBED';render()});render();loadItems();
