const URL="https://lhvbtioqqvvvprdmdhmi.supabase.co",KEY="sb_publishable_G8_JOzVzUvv1FXmsF31boQ_WbhPFZdS",db=supabase.createClient(URL,KEY);const STORES={eurospin:{name:'Eurospin',logo:'./eurospin.png'},esselunga:{name:'Esselunga',logo:'./esselunga.png'}};let store=null,items=[],connected=false,errorMsg='',shopping=false;
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function load(){const {data,error}=await db.from('shopping_items').select('*').order('created_at',{ascending:true});if(error){errorMsg=error.message;connected=false}else{items=data||[];connected=true;errorMsg=''}render()}
async function add(value){value=(value||document.getElementById('newitem')?.value||'').trim();if(!value||!store)return;const el=document.getElementById('newitem');if(el)el.value='';const {error}=await db.from('shopping_items').insert({store,item:value,checked:false});if(error){errorMsg=error.message;render()}}
async function toggle(id,v){await db.from('shopping_items').update({checked:!v}).eq('id',id)}
async function del(id){await db.from('shopping_items').delete().eq('id',id)}
async function finish(){await db.from('shopping_items').delete().eq('store',store).eq('checked',true);shopping=false;await load()}
function frequent(){const counts={};items.forEach(x=>{if(x.store===store)counts[x.item]=(counts[x.item]||0)+1});const defaults=store==='eurospin'?['Acqua','Yogurt greco','Pollo','Banane','Latte']:['Pane','Latte','Frutta','Pasta','Detersivo'];return [...new Set([...Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(x=>x[0]),...defaults])].slice(0,7)}
function home(){return `<div class="hero"><div style="font-size:44px">🛒</div><h1>Spesa</h1><p>Le nostre liste condivise</p></div><div class="stores">${Object.entries(STORES).map(([id,s])=>`<button class="store" onclick="store='${id}';render()"><img src="${s.logo}" alt="${s.name}"><div class="count">${items.filter(x=>x.store===id&&!x.checked).length} prodotti da comprare</div></button>`).join('')}</div>${status()}`}
function status(){return `<div class="status ${connected?'ok':'bad'}">${connected?'● Sincronizzato':'● '+esc(errorMsg||'Connessione...')}</div>`}
function list(){let a=items.filter(x=>x.store===store);if(shopping)a=[...a].sort((x,y)=>Number(x.checked)-Number(y.checked));const s=STORES[store];return `<div class="${shopping?'shopping':''}">${shopping?'<div class="modebar"><button class="done" onclick="finish()">✓ TERMINA SPESA</button></div>':`<div class="top"><button class="round" onclick="store=null;render()">‹</button><div class="brand"><img src="${s.logo}" alt="${s.name}"><div class="small">${a.filter(x=>!x.checked).length} da comprare</div></div><button class="round" onclick="load()">↻</button></div>`}${!shopping?`<div class="card"><div class="add"><input id="newitem" placeholder="Aggiungi un prodotto..." onkeydown="if(event.key==='Enter')add()"><button class="plus" onclick="add()">+</button></div></div><div class="section-title">⭐ PRODOTTI FREQUENTI</div><div class="frequent">${frequent().map(x=>`<button class="chip" onclick="add('${esc(x).replaceAll("'","&#39;")}')">+ ${esc(x)}</button>`).join('')}</div>`:''}<div class="section-title">${shopping?'TOCCA QUANDO PRENDI UN PRODOTTO':'LISTA'}</div><div style="display:flex;flex-direction:column">${a.length?a.map(x=>`<div class="item ${x.checked?'checked':''}"><button class="check" onclick="toggle(${x.id},${x.checked})"></button><span class="txt">${esc(x.item)}</span>${shopping?'':`<button class="trash" onclick="del(${x.id})">✕</button>`}</div>`).join(''):'<div class="empty">Lista vuota<br><small>Aggiungi il primo prodotto</small></div>'}</div>${!shopping&&a.length?'<button class="shopmode" onclick="shopping=true;render()">🛒 STO FACENDO LA SPESA</button>':''}${status()}</div>`}
function render(){document.getElementById('app').innerHTML=`<div class="app">${store?list():home()}</div>`}
db.channel('shopping-live-v2').on('postgres_changes',{event:'*',schema:'public',table:'shopping_items'},()=>load()).subscribe(s=>{connected=s==='SUBSCRIBED';render()});render();load();